"""autogenerated by genpy from jaco_driver/finger_position.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class finger_position(genpy.Message):
  _md5sum = "e7c67d780bd862da39ef8cc87274e040"
  _type = "jaco_driver/finger_position"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 Finger_1
float32 Finger_2
float32 Finger_3

"""
  __slots__ = ['Finger_1','Finger_2','Finger_3']
  _slot_types = ['float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Finger_1,Finger_2,Finger_3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(finger_position, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Finger_1 is None:
        self.Finger_1 = 0.
      if self.Finger_2 is None:
        self.Finger_2 = 0.
      if self.Finger_3 is None:
        self.Finger_3 = 0.
    else:
      self.Finger_1 = 0.
      self.Finger_2 = 0.
      self.Finger_3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.Finger_1, _x.Finger_2, _x.Finger_3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Finger_1, _x.Finger_2, _x.Finger_3,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.Finger_1, _x.Finger_2, _x.Finger_3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Finger_1, _x.Finger_2, _x.Finger_3,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3f = struct.Struct("<3f")
