"""autogenerated by genpy from jaco_driver/joint_angles.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class joint_angles(genpy.Message):
  _md5sum = "6cfb1df343eb134dbf80a50b505e0e1c"
  _type = "jaco_driver/joint_angles"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 Angle_J1
float32 Angle_J2
float32 Angle_J3
float32 Angle_J4
float32 Angle_J5
float32 Angle_J6
"""
  __slots__ = ['Angle_J1','Angle_J2','Angle_J3','Angle_J4','Angle_J5','Angle_J6']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Angle_J1,Angle_J2,Angle_J3,Angle_J4,Angle_J5,Angle_J6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(joint_angles, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Angle_J1 is None:
        self.Angle_J1 = 0.
      if self.Angle_J2 is None:
        self.Angle_J2 = 0.
      if self.Angle_J3 is None:
        self.Angle_J3 = 0.
      if self.Angle_J4 is None:
        self.Angle_J4 = 0.
      if self.Angle_J5 is None:
        self.Angle_J5 = 0.
      if self.Angle_J6 is None:
        self.Angle_J6 = 0.
    else:
      self.Angle_J1 = 0.
      self.Angle_J2 = 0.
      self.Angle_J3 = 0.
      self.Angle_J4 = 0.
      self.Angle_J5 = 0.
      self.Angle_J6 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.Angle_J1, _x.Angle_J2, _x.Angle_J3, _x.Angle_J4, _x.Angle_J5, _x.Angle_J6))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Angle_J1, _x.Angle_J2, _x.Angle_J3, _x.Angle_J4, _x.Angle_J5, _x.Angle_J6,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.Angle_J1, _x.Angle_J2, _x.Angle_J3, _x.Angle_J4, _x.Angle_J5, _x.Angle_J6))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Angle_J1, _x.Angle_J2, _x.Angle_J3, _x.Angle_J4, _x.Angle_J5, _x.Angle_J6,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
