/**
 *      _____
 *     /  _  \
 *    / _/ \  \
 *   / / \_/   \
 *  /  \_/  _   \  ___  _    ___   ___   ____   ____   ___   _____  _   _
 *  \  / \_/ \  / /  _\| |  | __| / _ \ | ++ \ | ++ \ / _ \ |_   _|| | | |
 *   \ \_/ \_/ /  | |  | |  | ++ | |_| || ++ / | ++_/| |_| |  | |  | +-+ |
 *    \  \_/  /   | |_ | |_ | ++ |  _  || |\ \ | |   |  _  |  | |  | +-+ |
 *     \_____/    \___/|___||___||_| |_||_| \_\|_|   |_| |_|  |_|  |_| |_|
 *             ROBOTICS™
 *
 *  File: kinova_ros_types.cpp
 *  Desc: Wrappers around Kinova structs to facilitate easier conversion to ROS
 *		  types.
 *  Auth: Alex Bencz
 *
 *  Copyright (c) 2013, Clearpath Robotics, Inc.
 *  All Rights Reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Clearpath Robotics, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL CLEARPATH ROBOTICS, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Please send comments, questions, or patches to skynet@clearpathrobotics.com
 *
 */

#include <math.h>
#include <angles/angles.h>
#include <tf/tf.h>
#include <kinova_driver/kinova_ros_types.h>
#include <string>


namespace kinova
{

// %Tag(converntion functions)%


// rads 0 to 2*M_PI
float normalizePositiveInRads(float rads)
{
    return static_cast<float>(angles::normalize_angle_positive(rads));
}

// rads -M_PI to M_PI
float normalizeInRads(float rads)
{
    return static_cast<float>(angles::normalize_angle(rads));
}

// degrees 0 to 360
float normalizePositiveInDegrees(float degrees)
{
    return angles::to_degrees(angles::normalize_angle_positive(angles::from_degrees(degrees)));
}

// degrees -180 to 180
float normalizeInDegrees(float degrees)
{
    return angles::to_degrees(angles::normalize_angle(angles::from_degrees(degrees)));
}

// %EndTag(converntion functions)%


bool areValuesClose(float first, float second, float tolerance)
{
    return ((first <= second + tolerance) && (first >= second - tolerance));
}


// Exceptions
// ----------
KinovaCommException::KinovaCommException(const std::string& message, const int error_code)
{
    std::stringstream ss;
        ss << "KinovaCommException: " << message << " (return code: " << error_code << ")" << std::endl;
    desc_ = ss.str();
}


const char* KinovaCommException::what() const throw()
{
    return desc_.c_str();
}


// Class definitions
// -----------------
/**
 * @brief obtain KinovaPosefrom geometry_msgs::Pose.
 *
 * obtain KinovaPose[X,Y,Z,ThetaX,ThetaY,ThetaZ] from geometry_msgs::Pose[x,y,z,qx,qy,qz,qw].
 * Euler angles[] are extracted from tf::Matrix3x3 EulerYPR = Rz(tz)*Ry(ty)*Rx(tx), where EulerYPR is generated by Quaterion.
 * Units are in meters and radians, The range of Euler angles are [-M_PI, M_PI)
 *
 * @param geometry_msgs ROS standard pose[x,y,z,qx,qy,qz,qw], in meters and quaterion.
 */
KinovaPose::KinovaPose(const geometry_msgs::Pose &pose)
{
    double tx, ty, tz;
    tf::Quaternion q;
    tf::quaternionMsgToTF(pose.orientation, q);

    tf::Matrix3x3 bt_q(q);

    // tf::Matrix3x3 EulerYPR = Rz(tz)*Ry(ty)*Rx(tx)
    bt_q.getEulerYPR(tz, ty, tx);

    X = static_cast<float>(pose.position.x);
    Y = static_cast<float>(pose.position.y);
    Z = static_cast<float>(pose.position.z);

    ThetaX = normalizeInRads(tx);
    ThetaY = normalizeInRads(ty);
    ThetaZ = normalizeInRads(tz);
}

/**
 * @brief obtain KinovaPosefrom CartesianInfo &pose.
 *
 * KinovaPose[X,Y,Z,ThetaX,ThetaY,ThetaZ]. position are in meters, and orientation is Euler-ZYX = Rz(ThetaZ)*Ry(ThetaY)*Rx(ThetaX). The range of Euler angles are [-M_PI, M_PI)
 *
 * @param pose CartesianInfo units are in meters and degrees
 */
KinovaPose::KinovaPose(const CartesianInfo &pose)
{
    X = pose.X;
    Y = pose.Y;
    Z = pose.Z;

    ThetaX = normalizeInRads(pose.ThetaX);
    ThetaY = normalizeInRads(pose.ThetaY);
    ThetaZ = normalizeInRads(pose.ThetaZ);
}

/**
 * @brief construct geometric::Pose message from KinovaPose
 * @return geometry_msgs::Pose[x,y,z,qx,qy,qz,qw] position in meters, orientation is in Quaternion.
 */
geometry_msgs::Pose KinovaPose::constructPoseMsg()
{
    geometry_msgs::Pose pose;
    tf::Quaternion position_quaternion;

   // setEulerZYX(tz, ty, tx) == setRPY(tx, ty, tz) == = mz * my * mx. the previous is Euler angle rotating with temp axis, while latter rotates with fixed axis.
//  position_quaternion.setEulerZYX(ThetaZ, ThetaY, ThetaX);
    position_quaternion.setRPY(ThetaX, ThetaY, ThetaZ);

    tf::quaternionTFToMsg(position_quaternion, pose.orientation);

    pose.position.x = X;
    pose.position.y = Y;
    pose.position.z = Z;

    return pose;
}

/**
 * @brief construct geometric::Wrench message from KinovaPose data structure
 *
 * KinovaPose[X,Y,Z,ThetaX,ThetaY,ThetaZ] doesn't store pose information in this case. Instead, it stores force and torque correspondingly.
 *
 * @return geometry_msgs [Fx,Fy,Fz,Tx,Ty,Tz] in Newton and Nm.
 */
geometry_msgs::Wrench KinovaPose::constructWrenchMsg()
{
    geometry_msgs::Wrench wrench;

    wrench.force.x  = X;
    wrench.force.y  = Y;
    wrench.force.z  = Z;
    wrench.torque.x = ThetaX;
    wrench.torque.y = ThetaY;
    wrench.torque.z = ThetaZ;

    return wrench;
}


/**
 * @brief check all the position and orientation values, to determine if current KinovaPose reach "other"
 *
 * @param other the pose to be compared with, normally the motion goal. In meters and radians.
 * @param position_tolerance  threshold to be considered as identical between two position values in the same axis.
 * @param EulerAngle_tolerance threshold to be considered as identical between two EulerAngle values along the same axis.
 * @return true if both position and orientation can be considerred identical.
 */
bool KinovaPose::isCloseToOther(const KinovaPose &other, float position_tolerance, float EulerAngle_tolerance) const
{
    bool status = true;
    status = status && areValuesClose(X, other.X, position_tolerance);
    status = status && areValuesClose(Y, other.Y, position_tolerance);
    status = status && areValuesClose(Z, other.Z, position_tolerance);
    status = status && areValuesClose(ThetaX, other.ThetaX, EulerAngle_tolerance);
    status = status && areValuesClose(ThetaY, other.ThetaY, EulerAngle_tolerance);
    status = status && areValuesClose(ThetaZ, other.ThetaZ, EulerAngle_tolerance);
    return status;
}

/**
 * @brief KinovaAngles[Actuator1 ... Actuator6] stores 6 joint values in degrees
 *
 * KinovaAngles[Actuator1 ... Actuator6] can go beyond the range of [0 360]
 *
 * @param angles in degrees
 */
KinovaAngles::KinovaAngles(const kinova_msgs::JointAngles &angles)
{

    Actuator1 = angles.joint1;
    Actuator2 = angles.joint2;
    Actuator3 = angles.joint3;
    Actuator4 = angles.joint4;
    Actuator5 = angles.joint5;
    Actuator6 = angles.joint6;
}

/**
 * @brief KinovaAngles[Actuator1 ... Actuator6] stores 6 joint values in degrees
 * @param angles in degrees
 */
KinovaAngles::KinovaAngles(const AngularInfo &angles)
{
    Actuator1 = angles.Actuator1;
    Actuator2 = angles.Actuator2;
    Actuator3 = angles.Actuator3;
    Actuator4 = angles.Actuator4;
    Actuator5 = angles.Actuator5;
    Actuator6 = angles.Actuator6;
}

/**
 * @brief KinovaAngles::constructAnglesMsg
 * @return kinova_msgs::JointAngles is used as messanges for topic in ROS, in degrees.
 */
kinova_msgs::JointAngles KinovaAngles::constructAnglesMsg()
{
    kinova_msgs::JointAngles angles;
    angles.joint1 = Actuator1;
    angles.joint2 = Actuator2;
    angles.joint3 = Actuator3;
    angles.joint4 = Actuator4;
    angles.joint5 = Actuator5;
    angles.joint6 = Actuator6;
    return angles;
}


/**
 * @brief check all the joint values, to determine if current KinovaAngles reach "other"
 * @param other joint angles to be compared with, in degrees.
 * @param tolerance threshold to be considered as identical between two joints.
 * @return true if all joint values can be considerred identical.
 */
bool KinovaAngles::isCloseToOther(const KinovaAngles &other, float tolerance) const
{
    bool status = true;
    status = status && areValuesClose(Actuator1, other.Actuator1, tolerance);
    status = status && areValuesClose(Actuator2, other.Actuator2, tolerance);
    status = status && areValuesClose(Actuator3, other.Actuator3, tolerance);
    status = status && areValuesClose(Actuator4, other.Actuator4, tolerance);
    status = status && areValuesClose(Actuator5, other.Actuator5, tolerance);
    status = status && areValuesClose(Actuator6, other.Actuator6, tolerance);
    return status;
}


FingerAngles::FingerAngles(const kinova_msgs::FingerPosition &position)
{
    Finger1 = position.finger1;
    Finger2 = position.finger2;
    Finger3 = position.finger3;
}


FingerAngles::FingerAngles(const FingersPosition &angle)
{
    Finger1 = angle.Finger1;
    Finger2 = angle.Finger2;
    Finger3 = angle.Finger3;
}


kinova_msgs::FingerPosition FingerAngles::constructFingersMsg()
{
    kinova_msgs::FingerPosition angles;
    angles.finger1 = Finger1;
    angles.finger2 = Finger2;
    angles.finger3 = Finger3;
    return angles;
}


bool FingerAngles::isCloseToOther(const FingerAngles &other, float tolerance) const
{
    bool status = true;
    status = status && areValuesClose(Finger1, other.Finger1, tolerance);
    status = status && areValuesClose(Finger2, other.Finger2, tolerance);
    status = status && areValuesClose(Finger3, other.Finger3, tolerance);
    return status;
}

}  // namespace kinova
