var annotated =
[
    [ "AngularAcceleration", "struct_angular_acceleration.html", "struct_angular_acceleration" ],
    [ "AngularInfo", "struct_angular_info.html", "struct_angular_info" ],
    [ "AngularPosition", "struct_angular_position.html", "struct_angular_position" ],
    [ "ButtonEvents", "struct_button_events.html", "struct_button_events" ],
    [ "CartesianInfo", "struct_cartesian_info.html", "struct_cartesian_info" ],
    [ "CartesianPosition", "struct_cartesian_position.html", "struct_cartesian_position" ],
    [ "ClientConfigurations", "struct_client_configurations.html", "struct_client_configurations" ],
    [ "ControlMapping", "struct_control_mapping.html", "struct_control_mapping" ],
    [ "ControlMappingCharts", "struct_control_mapping_charts.html", "struct_control_mapping_charts" ],
    [ "ControlsModeMap", "struct_controls_mode_map.html", "struct_controls_mode_map" ],
    [ "Finger", "struct_finger.html", "struct_finger" ],
    [ "FingersPosition", "struct_fingers_position.html", "struct_fingers_position" ],
    [ "ForcesInfo", "struct_forces_info.html", "struct_forces_info" ],
    [ "GeneralInformations", "struct_general_informations.html", "struct_general_informations" ],
    [ "Gripper", "struct_gripper.html", "struct_gripper" ],
    [ "JoystickCommand", "struct_joystick_command.html", "struct_joystick_command" ],
    [ "Limitation", "struct_limitation.html", "struct_limitation" ],
    [ "PeripheralInfo", "struct_peripheral_info.html", "struct_peripheral_info" ],
    [ "QuickStatus", "struct_quick_status.html", "struct_quick_status" ],
    [ "SensorsInfo", "struct_sensors_info.html", "struct_sensors_info" ],
    [ "SingularityVector", "struct_singularity_vector.html", null ],
    [ "StickEvents", "struct_stick_events.html", "struct_stick_events" ],
    [ "SystemError", "struct_system_error.html", "struct_system_error" ],
    [ "SystemStatus", "struct_system_status.html", "struct_system_status" ],
    [ "TrajectoryFIFO", "struct_trajectory_f_i_f_o.html", "struct_trajectory_f_i_f_o" ],
    [ "TrajectoryPoint", "struct_trajectory_point.html", "struct_trajectory_point" ],
    [ "UserPosition", "struct_user_position.html", "struct_user_position" ],
    [ "Zone", "struct_zone.html", "struct_zone" ],
    [ "ZoneLimitation", "struct_zone_limitation.html", "struct_zone_limitation" ],
    [ "ZoneList", "struct_zone_list.html", "struct_zone_list" ],
    [ "ZoneShape", "struct_zone_shape.html", "struct_zone_shape" ]
];